# Generated by Django 3.2 on 2022-03-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedisciplina',
            name='periodoGradeAtual',
            field=models.IntegerField(default=0, help_text='Período da disciplina na grade atual', null=True),
        ),
        migrations.AlterField(
            model_name='gradedisciplina',
            name='periodo',
            field=models.IntegerField(default=0, help_text='Período na qual a disciplina é fixada'),
        ),
    ]
