# Generated by Django 3.2 on 2022-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0002_auto_20220313_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedisciplina',
            name='periodo',
            field=models.IntegerField(default=0, help_text='Período na qual a disciplina é fixada', null=True),
        ),
    ]
