# Generated by Django 3.2 on 2022-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0003_alter_gradedisciplina_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedisciplina',
            name='retencao',
            field=models.FloatField(default=0, help_text='Retenção dgrades do a disciplina'),
        ),
    ]
