# Generated by Django 3.2 on 2022-03-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0007_alter_gradedisciplinacursar_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='emBalanceamento',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
