# Generated by Django 3.2 on 2022-04-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0009_grade_balanceamentointerrompido'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='parar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
