# Generated by Django 3.2 on 2022-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0010_grade_parar'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='problemaUltimoBalanceamento',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
