# Generated by Django 3.2 on 2022-04-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0012_remove_grade_problemaultimobalanceamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='problemaUltimoBalanceamento',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
