# Generated by Django 5.1.1 on 2024-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricular', '0013_grade_problemaultimobalanceamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='periodoCronologico',
            field=models.IntegerField(help_text='Período contínuo em que se encontra o aluno', null=True),
        ),
    ]
