from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url
from . import views

# urlpatterns = [
#     # path('', views.index, name='curricular_index'),
#     # path('create-new', views.create_new, name='instituicao_create'),
#     # path('view/<int:instituicao_id>', views.view, name='instituicao_view'),
#     # path('edit/<int:instituicao_id>', views.edit, name='instituicao_edit'),
#     # path('delete/<int:instituicao_id>', views.delete, name='instituicao_delete'),
# ]
urlpatterns = [

path('admin/instituicao', views.instituicao_index, name='instituicao_index'),
path('admin/instituicao/create', views.instituicao_create, name='instituicao_create'),
path('admin/instituicao/view/<int:instituicao_id>', views.instituicao_view, name='instituicao_view'),
path('admin/instituicao/edit/<int:instituicao_id>', views.instituicao_edit, name='instituicao_edit'),
path('admin/instituicao/delete/<int:instituicao_id>', views.instituicao_delete, name='instituicao_delete'),

path('admin/curso', views.curso_index, name='curso_index'),
path('admin/curso/create', views.curso_create, name='curso_create'),
path('admin/curso/view/<int:curso_id>', views.curso_view, name='curso_view'),
path('admin/curso/edit/<int:curso_id>', views.curso_edit, name='curso_edit'),
path('admin/curso/delete/<int:curso_id>', views.curso_delete, name='curso_delete'),

path('admin/disciplina', views.disciplina_index, name='disciplina_index'),
path('admin/disciplina/create', views.disciplina_create, name='disciplina_create'),
path('admin/disciplina/view/<int:disciplina_id>', views.disciplina_view, name='disciplina_view'),
path('admin/disciplina/edit/<int:disciplina_id>', views.disciplina_edit, name='disciplina_edit'),
path('admin/disciplina/delete/<int:disciplina_id>', views.disciplina_delete, name='disciplina_delete'),

path('admin/curriculo', views.curriculo_index, name='curriculo_index'),
path('admin/curriculo/create', views.curriculo_create, name='curriculo_create'),
path('admin/curriculo/view/<int:curriculo_id>', views.curriculo_view, name='curriculo_view'),
path('admin/curriculo/edit/<int:curriculo_id>', views.curriculo_edit, name='curriculo_edit'),
path('admin/curriculo/delete/<int:curriculo_id>', views.curriculo_delete, name='curriculo_delete'),

path('admin/grade', views.grade_index, name='grade_index'),
path('admin/grade/create', views.grade_create, name='grade_create'),

path('admin/grade/view/<int:grade_id>', views.grade_view, name='grade_view'),
path('admin/grade/edit/<int:grade_id>', views.grade_edit, name='grade_edit'),
path('admin/grade/delete/<int:grade_id>', views.grade_delete, name='grade_delete'),
path('admin/grade/balance/<int:grade_id>', views.grade_balance, name='grade_balance'),
# url(r'^ajax/balance/$', views.grade_balance, name='grade_balance'),
path('admin/grade/deletesolucoes/<int:grade_id>', views.grade_delete_solucoes, name='grade_delete_solucoes'),
path('admin/grade/relatorioanalise/<int:grade_id>', views.grade_relatorio_analise, name='grade_relatorio_analise'),
path('admin/grade/relatorioanalisegrades', views.grade_relatorio_analise_grades,
     name='grade_relatorio_analise_grades'),
path('admin/grade/relatorio/<int:grade_id>', views.grade_relatorio, name='grade_relatorio'),
path('admin/grade/atualizavariavelpararotimizacao/<int:grade_id>', views.grade_atualiza_variavel_parar_otimizacao,
     name='grade_atualiza_variavel_parar_otimizacao'),
path('admin/grade/gradebalancefirst/<int:grade_id>', views.grade_balance_first, name='grade_balance_first'),

path('admin/gradedisciplina', views.gradedisciplina_index, name='gradedisciplina_index'),
path('admin/gradedisciplina/create/<int:grade_id>', views.gradedisciplina_create, name='gradedisciplina_create'),
# path('admin/gradedisciplina/consolidar/<int:grade_id>', views.gradedisciplina_consolidar, name='gradedisciplina_consolidar'),
path('admin/gradedisciplina/create', views.gradedisciplina_create, name='gradedisciplina_create'),
path('admin/gradedisciplina/view/<int:gradedisciplina_id>', views.gradedisciplina_view,
     name='gradedisciplina_view'),
path('admin/gradedisciplina/edit/<int:gradedisciplina_id>', views.gradedisciplina_edit,
     name='gradedisciplina_edit'),
path('admin/gradedisciplina/delete/<int:gradedisciplina_id>', views.gradedisciplina_delete,
     name='gradedisciplina_delete'),

path('admin/relacionamento', views.relacionamento_index, name='relacionamento_index'),
path('admin/relacionamento/create/<int:grade_id>', views.relacionamento_create, name='relacionamento_create'),
path('admin/relacionamento/create', views.relacionamento_create, name='relacionamento_create'),
path('admin/relacionamento/view/<int:relacionamento_id>', views.relacionamento_view, name='relacionamento_view'),
path('admin/relacionamento/edit/<int:relacionamento_id>', views.relacionamento_edit, name='relacionamento_edit'),
path('admin/relacionamento/delete/<int:relacionamento_id>', views.relacionamento_delete,
     name='relacionamento_delete'),

path('admin/requisito', views.requisito_index, name='requisito_index'),
path('admin/requisito/create/<int:grade_id>', views.requisito_create, name='requisito_create'),
path('admin/requisito/create', views.requisito_create, name='requisito_create'),
path('admin/requisito/view/<int:gradeDisciplina_id>', views.requisito_view, name='requisito_view'),
path('admin/requisito/edit/<int:gradeDisciplina_id>', views.requisito_edit, name='requisito_edit'),
path('admin/requisito/delete/<int:gradeDisciplina_id>', views.requisito_delete, name='requisito_delete'),

path('aluno/grade', views.aluno_grade_index, name='aluno_grade_index'),
path('aluno/grade/gradealuno', views.aluno_grade_gradealuno, name='aluno_grade_gradealuno'),
path('aluno/grade/gradealuno/<int:grade_id>', views.aluno_grade_gradealuno, name='aluno_grade_gradealuno'),
path('aluno/grade/create', views.aluno_grade_create, name='aluno_grade_create'),
path('aluno/grade/create/<int:grade_id>', views.aluno_grade_create, name='aluno_grade_create'),
path('aluno/grade/edit/<int:grade_id>', views.aluno_grade_edit, name='aluno_grade_edit'),
path('aluno/grade/view/<int:grade_id>', views.aluno_grade_view, name='aluno_grade_view'),
path('aluno/grade/delete/<int:grade_id>', views.aluno_grade_delete, name='aluno_grade_delete'),
path('aluno/grade/balance/<int:grade_id>', views.aluno_grade_balance, name='aluno_grade_balance'),
path('aluno/grade/deletesolucoes/<int:grade_id>', views.aluno_grade_delete_solucoes,
     name='aluno_grade_delete_solucoes'),
path('aluno/grade/deletedisciplinascursar/<int:grade_id>', views.aluno_grade_delete_disciplinas_cursar,
     name='aluno_grade_delete_disciplinas_cursar'),
path('aluno/grade/relatorioanalise/<int:grade_id>', views.aluno_grade_relatorio_analise,
     name='aluno_grade_relatorio_analise'),
path('aluno/grade/relatorio/<int:grade_id>', views.aluno_grade_relatorio, name='aluno_grade_relatorio'),
path('aluno/grade/gradesbalanceadas', views.aluno_gradesbalanceadas_index, name='aluno_gradesbalanceadas_index'),
path('aluno/grade/gradesbalanceadas/<int:grade_id>', views.aluno_gradesbalanceadas_index, name='aluno_gradesbalanceadas_index'),
path('aluno/grade/gradebalancefirst/<int:grade_id>', views.aluno_grade_balance_first,
     name='aluno_grade_balance_first'),

path('aluno/gradedisciplina/create', views.aluno_gradedisciplina_create, name='aluno_gradedisciplina_create'),
path('aluno/gradedisciplina/create/<int:grade_id>', views.aluno_gradedisciplina_create,
     name='aluno_gradedisciplina_create'),
path('aluno/gradedisciplina', views.aluno_gradedisciplina_index, name='aluno_gradedisciplina_index'),
path('aluno/gradedisciplina/view/<int:gradedisciplinacursar_id>', views.aluno_gradedisciplina_view,
     name='aluno_gradedisciplina_view'),
path('aluno/gradedisciplina/edit/<int:gradedisciplinacursar_id>', views.aluno_gradedisciplina_edit,
     name='aluno_gradedisciplina_edit'),
path('aluno/gradedisciplina/delete/<int:gradedisciplinacursar_id>', views.aluno_gradedisciplina_delete,
     name='aluno_gradedisciplina_delete'),

path('comum/usercurso', views.comum_usercurso_index, name='comum_usercurso_index'),
path('comum/usercurso/create', views.comum_usercurso_create, name='comum_usercurso_create'),
path('comum/usercurso/view/<int:curso_id>', views.comum_usercurso_view, name='comum_usercurso_view'),
path('comum/usercurso/delete/<int:usercurso_id>', views.comum_usercurso_delete, name='comum_usercurso_delete'),

path('', views.home, name="home"),
path('comum/sobre', views.sobre, name="sobre"),
path('login/', views.login_user, name='login'),
path('logout/', views.logout_user, name='logout'),
path('register/', views.register_user, name='register'),
path('edit_profile/', views.edit_profile, name='edit_profile'),
path('change_password', views.change_password, name='change_password'),

]
